/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carui;
import java.io.File;
import javax.swing.ImageIcon;
import java.util.Set;
import javax.swing.JOptionPane;
import model.Car;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import java.awt.Image;

/**
 *
 * @author meghanshubhatt
 */
public class CreateJPanelCar extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanelCar
     */
    Car car;
    public String selectedImagePath;
    private ArrayList alist = new ArrayList();
    public CreateJPanelCar(Car car) {
        initComponents();
        this.car = car;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumber = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        lblEngineNo = new javax.swing.JLabel();
        lblCarPhoto = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblOwnerAddress = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        txtEngineNo = new javax.swing.JTextField();
        lblDrvingLicense = new javax.swing.JLabel();
        txtTotalSeats = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        txtDrivingLicense = new javax.swing.JTextField();
        lblTotalSeats = new javax.swing.JLabel();
        txtWarrantyYear = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblOwnerName = new javax.swing.JLabel();
        lblLicensePlate = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblServiceRecords = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        lblWarrantyYear = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtServiceRecords = new javax.swing.JTextField();
        lblOwnerTelephoneNumber = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAddServiceRecord = new javax.swing.JButton();
        lblImageDisplay = new javax.swing.JLabel();
        btnBrowseImage = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        txtNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblPhoto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPhoto.setText("Photo:");

        lblEngineNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEngineNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEngineNo.setText("Engine No.*:");

        lblCarPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carui/CarImage.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Please Enter Your Details ! :)");

        lblOwnerAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblOwnerAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOwnerAddress.setText("Owner Address*:");

        lblEmailAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEmailAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmailAddress.setText("Email Address*:");

        txtEmailAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtEmailAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEmailAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtColor.setBackground(new java.awt.Color(204, 204, 204));
        txtColor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtYear.setBackground(new java.awt.Color(204, 204, 204));
        txtYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblBrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrand.setText("Brand:");

        txtEngineNo.setBackground(new java.awt.Color(204, 204, 204));
        txtEngineNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEngineNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblDrvingLicense.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDrvingLicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrvingLicense.setText("Driving License*:");

        txtTotalSeats.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalSeats.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTotalSeats.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblModel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModel.setText("Model:");

        txtLicensePlate.setBackground(new java.awt.Color(204, 204, 204));
        txtLicensePlate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLicensePlate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDrivingLicense.setBackground(new java.awt.Color(204, 204, 204));
        txtDrivingLicense.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDrivingLicense.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblTotalSeats.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTotalSeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalSeats.setText("Total Seat's*:");

        txtWarrantyYear.setBackground(new java.awt.Color(204, 204, 204));
        txtWarrantyYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWarrantyYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblColor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor.setText("Color:");

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblOwnerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblOwnerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOwnerName.setText("Owner Name*:");

        lblLicensePlate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLicensePlate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicensePlate.setText("License Plate*:");

        lblSSN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSSN.setText("Owner SSN*:");

        lblServiceRecords.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblServiceRecords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServiceRecords.setText("Service Records:");

        txtOwnerName.setBackground(new java.awt.Color(204, 204, 204));
        txtOwnerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtOwnerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblWarrantyYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWarrantyYear.setText("Warranty Year*:");

        lblYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYear.setText("Year:");

        txtServiceRecords.setBackground(new java.awt.Color(204, 204, 204));
        txtServiceRecords.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtServiceRecords.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblOwnerTelephoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblOwnerTelephoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOwnerTelephoneNumber.setText("Owner Phone Number*:");

        txtBrand.setBackground(new java.awt.Color(204, 204, 204));
        txtBrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtSSN.setBackground(new java.awt.Color(204, 204, 204));
        txtSSN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSSN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtModel.setBackground(new java.awt.Color(204, 204, 204));
        txtModel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtModel.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSave.setText("Save !");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAddServiceRecord.setText("Add Service Records");
        btnAddServiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceRecordActionPerformed(evt);
            }
        });

        lblImageDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBrowseImage.setText("Browse Image");
        btnBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCarPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblEngineNo)
                            .addGap(37, 37, 37))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblBrand)
                                .addComponent(lblColor)
                                .addComponent(lblModel))
                            .addGap(73, 73, 73)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblWarrantyYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblYear)
                            .addComponent(lblTotalSeats)
                            .addComponent(lblLicensePlate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailAddress)
                            .addComponent(lblDrvingLicense)
                            .addComponent(lblSSN)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblOwnerAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblServiceRecords, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnAddServiceRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDrivingLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtServiceRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOwnerTelephoneNumber)
                            .addComponent(lblOwnerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPhoto)
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBrowseImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblImageDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGap(66, 66, 66))))))
            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCarPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrvingLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDrivingLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOwnerAddress)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblServiceRecords)
                            .addComponent(txtServiceRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowseImage)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWarrantyYear)
                        .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddServiceRecord)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //System.out.println(car.setBrand(txtBrand.getText()));
        
        // BRAND
//        if (txtBrand.getText().trim().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Car Brand is Empty!");
//            txtBrand.grabFocus();
//            return;
//        }
//        else
//        {car.setBrand(txtBrand.getText());}
            car.setBrand(txtBrand.getText());
        
        
        // MODEL
//        if (txtModel.getText().trim().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Car Model is Empty!");
//            txtModel.grabFocus();
//            return;
//        }
//        else
//        {car.setModel(txtModel.getText());}
            car.setModel(txtModel.getText());
        
        // COLOR
//        if (txtColor.getText().trim().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Car Color is Empty!");
//            txtColor.grabFocus();
//            return;
//        }
//        else
//        {car.setColor(txtColor.getText());}
            car.setColor(txtColor.getText());
        
        // ENGINE NO
        if (txtEngineNo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Car Engine Number is Empty!");
            txtEngineNo.grabFocus();
            return;
        }
        else
        {car.setEngineNo(txtEngineNo.getText());}        

       
        // Integer.parseInt(s)
        
        // TOTAL SEATS
        try{
            Integer.parseInt(txtTotalSeats.getText());
            car.setSeatsNumber(txtTotalSeats.getText());
        }
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this, "Put proper Number in Total Seats !");
            txtTotalSeats.grabFocus();
            return;
        }
        
        
        // LICENSE PLATE
        if (txtLicensePlate.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "License Plate Number is Empty!");
            txtLicensePlate.grabFocus();
            return;
        }
        else
        {   
            car.setLicensePlates(txtLicensePlate.getText());} 
        
        
        // OWNER NAME
        if (txtOwnerName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Owner Name is Empty!");
            txtOwnerName.grabFocus();
            return;
        }
        else
        {car.setOwnerName(txtOwnerName.getText());} 
        
        
        // PHONE NUMBER
        try{
            long phoneNumber = Long.parseLong(txtNumber.getText());
            
            if (String.valueOf(phoneNumber).length() != 10)
                    {
                        JOptionPane.showMessageDialog(this, "Input Valid Telephone Number !");
                        txtNumber.grabFocus();
                        return;
                        
                    }
            
            car.setOwnerTelephoneNumbers(txtNumber.getText());
        }
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this, "Input Valid Telephone Number !");
            txtNumber.grabFocus();
            return;
        }    
        
        
        // YEAR
        try{
            int year = Integer.parseInt(txtYear.getText());
            
            if (String.valueOf(year).length() != 4)
                    {
                        JOptionPane.showMessageDialog(this, "Input Valid Year !");
                        txtYear.grabFocus();
                        return;
                        
                    }
            
            car.setYear(txtYear.getText());
        }
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this, "Input Valid Year !");
            txtYear.grabFocus();
            return;
        } 
        
        // EMAIL ADDRESS
        if (txtEmailAddress.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Email Address is Empty!");
            txtEmailAddress.grabFocus();
            return;
        }
        else
        {car.setOwnerEmailAddresses(txtEmailAddress.getText());}
        
        // DRIVING LICENSE
        
        if (txtDrivingLicense.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Driving License Number is Empty!");
            txtDrivingLicense.grabFocus();
            return;
        }
        else
        {car.setOwnerDriverLicense(txtDrivingLicense.getText());} 
       
        // SSN 9 digit
        try{
            long ssn = Long.parseLong(txtSSN.getText());
            
            if (String.valueOf(ssn).length() != 9)
                    {
                        JOptionPane.showMessageDialog(this, "Input Valid SSN !");
                        txtSSN.grabFocus();
                        return;
                        
                    }
            
            car.setOwnerSocialSecurityNumber(txtSSN.getText());
        }
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this, "Input Valid SSN !");
            txtSSN.grabFocus();
            return;
        } 
        
        
        // OWNER ADDRESS
        if (txtAddress.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Owner Address is Empty!");
            txtAddress.grabFocus();
            return;
        }
        else
        {car.setOwnerAddress(txtAddress.getText());}
        

        // SERVICE RECORDS
        car.setServiceRecords(alist);
        // WARRANTY YEAR
        try{
            int year = Integer.parseInt(txtWarrantyYear.getText());
            
            if (String.valueOf(year).length() != 4)
                    {
                        JOptionPane.showMessageDialog(this, "Input Valid Warranty Year !");
                        txtWarrantyYear.grabFocus();
                        return;
                        
                    }
            
            car.setWarrantyYear(txtWarrantyYear.getText());
        }
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this, "Input Valid Warranty Year !");
            txtWarrantyYear.grabFocus();
            return;
        } 
        
        
        // PHOTO
        
        //car.setPhoto(txtPhoto.getText());
        //System.out.println(selectedImagePath);
        JOptionPane.showMessageDialog(this, "Car Information Saved !");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddServiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceRecordActionPerformed
        // TODO add your handling code here:
        alist.add(txtServiceRecords.getText());
        System.out.println(alist);
        txtServiceRecords.setText("");
        
        
    }//GEN-LAST:event_btnAddServiceRecordActionPerformed

    private void btnBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser btnBrowseImage = new JFileChooser();
        int showOpenDialogue =  btnBrowseImage.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = btnBrowseImage.getSelectedFile();
            //selectedImagePath = selectedImageFile.getAbsolutePath();
            //JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            ImageIcon ii = new ImageIcon(selectedImageFile.toString());
//            Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblImageDisplay.getWidth(), lblImageDisplay.getHeight(), Image.SCALE_SMOOTH);
             
            lblImageDisplay.setIcon(new ImageIcon(image));
            JOptionPane.showMessageDialog(this, "Image Uploaded !");
            car.setPhoto(image);
            //System.out.println(image);
        }
    }//GEN-LAST:event_btnBrowseImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddServiceRecord;
    private javax.swing.JButton btnBrowseImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCarPhoto;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDrvingLicense;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblImageDisplay;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOwnerAddress;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerTelephoneNumber;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblServiceRecords;
    private javax.swing.JLabel lblTotalSeats;
    private javax.swing.JLabel lblWarrantyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDrivingLicense;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtServiceRecords;
    private javax.swing.JTextField txtTotalSeats;
    private javax.swing.JTextField txtWarrantyYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
